### PR TITLE
Add documentation for promise APIs

### PR DESCRIPTION
**Pull request by rockwotj**

### CODE REVIEW

**Review by saghul — APPROVED** [review]

**Comment by rockwotj** [comment]
Gentle ping on this, is there anything needed here to merge?

**Comment by saghul** [comment]
Thanks for the reminder!

**Comment by chqrlie** [comment]
Note however that the definition should be parenthesized:
```
#define JS_INVALID_PROMISE_STATE  (-1)
```

**Comment by rockwotj** [comment]
Ah good catch. Macros are such a clunky way to define constants. I can submit a fix later this weekend.

**Pull request merged**
