### PR TITLE
Remove non-standard properties from Function.prototype

### PR DESCRIPTION
**Pull request by saghul**
Closes: https://github.com/quickjs-ng/quickjs/discussions/713

### CODE REVIEW

**Comment by bnoordhuis** [comment]
So... I'm acutely aware they're non-standard but they're also pretty useful.

**Comment by saghul** [comment]
I have no strong opinion TBH.

I made the PR in case we concluded we wanted them out.

For documentation purposes: what use do you have for them?

**Comment by bnoordhuis** [comment]
I guess it's a little debug tool because it tells you where a function object comes from.

**Comment by saghul** [comment]
I'm ok with having it.

**Pull request closed without merging**
