### PR TITLE
Remove custom __getClass method

### PR DESCRIPTION
**Pull request by saghul**

### CODE REVIEW

**Review by bnoordhuis — APPROVED** [review]
:+1:

**Comment by chqrlie** [comment]
Why not use `a.constructor === RegExp` or possibly `a?.constructor === RegExp` ?

**Comment by bnoordhuis** [comment]
That won't work if they're from different realms/contexts, right?

**Comment by chqrlie** [comment]
> Why not use `a.constructor === RegExp` or possibly `a?.constructor === RegExp`

I guess we could use `a.constructor.name === 'RegExp'` or `a?.constructor?.name === 'RegExp'` then.

A simpler way to test this is `a instanceof RegExp`.  `RegExp` should be the original value of `globalThis.RegExp`, like the other builtin object constructors.  If these constructors are different in a different realm, using the constructor name solves this for actual instances.  Too bad if the user refines a `RegExp` constructor that does something incompatible.

Same problem with `a instanceof Date`.

**Comment by saghul** [comment]
I followed what seems to be the most used convention to test for Regex objects.

**Comment by chqrlie** [comment]
> I followed what seems to be the most used convention to test for Regex objects.

OK, classical idiom I suppose. I tend to prefer a simpler idiom that does not involve a function call nor allocate memory.

**Comment by bnoordhuis** [comment]
Right, but this is in the repl where performance isn't much of a concern.

**Comment by chqrlie** [comment]
> Right, but this is in the repl where performance isn't much of a concern.

I still suggest `a?.constructor?.name === 'RegExp' and `a?.constructor?.name === 'Date'`

**Comment by saghul** [comment]
Changed it to `instanceof` like we do for `Date`. It's a repl, so we don't need to go the extra mile IMHO. If the user wants to monkey around with objects, more power to them.

**Comment by chqrlie** [comment]
> Changed it to `instanceof` like we do for `Date`. It's a repl, so we don't need to go the extra mile IMHO. If the user wants to monkey around with objects, more power to them.

Ben's objection was that objects created in a different *realm* would not be instances of the same constructors.  This is correct, but we do not have support in repl for different realms at the moment.

V8 has a global object `Realm` with functions to create and handle different realms. This seems to be an extension that is not proposed for tc39.  Should we implement it?

**Comment by saghul** [comment]
Any chance `ShadowRealm` is close to that? https://github.com/tc39/proposal-shadowrealm

**Comment by chqrlie** [comment]
> Any chance `ShadowRealm` is close to that? https://github.com/tc39/proposal-shadowrealm

It goes in the same direction, but with a different approach: different object/function names and semantics

**Comment by saghul** [comment]
Since the old one never got anywhere I'd say we shouldn't support it.

**Pull request merged**
