### PR TITLE
Make `Object.prototype` an immutable prototype object

### PR DESCRIPTION
**Pull request by chqrlie**

### CODE REVIEW

**Comment by bnoordhuis** [comment]
Huh. The change itself LGTM but the linux-msan failure looks quite possibly related, if inexplicable.

**Comment by bnoordhuis** [comment]
The linux-msan buildbot also failed on another pull request (albeit in a different manner) so it may not be anything related to this pull request.

edit: tried to reproduce locally, failed.

**Comment by chqrlie** [comment]
My checkout is broken beyond fixing, I shall resubmit this from a clean new fork.

**Comment by chqrlie** [comment]
> The linux-msan buildbot also failed on another pull request (albeit in a different manner) so it may not be anything related to this pull request.
> 
> edit: tried to reproduce locally, failed.

Yes these failures are inexplicable, I shall resubmit later.

**Comment by bnoordhuis** [comment]
> My checkout is broken beyond fixing, I shall resubmit this from a clean new fork.

You can almost always salvage your branches with judicious use of `git fetch` + `git rebase -i` (or non-interactive rebase). `git reflog` is a lifesaver too, sometimes.

**Pull request closed without merging**
