### PR TITLE
Add / adapt upstream fixes

### PR DESCRIPTION
**Pull request by saghul**

### CODE REVIEW

**Comment by bnoordhuis** [comment]
I think we don't need `-fwrapv`, the ubsan buildbot should catch (and, in the past, has caught) instances of signed integer overflow.

**Review by bnoordhuis — APPROVED** [review]

**Comment by saghul** [comment]
> I think we don't need `-fwrapv`, the ubsan buildbot should catch (and, in the past, has caught) instances of signed integer overflow.

Does it hurt to have it? I don't mind dropping that commit.

**Comment by saghul** [comment]
@bnoordhuis Added one last commit, PTAL.

Note I omitted this part https://github.com/bellard/quickjs/commit/4bb8c35da7c83b5eb67541772b857e822da855da#diff-45f1ae674139f993bf8a99c382c1ba4863272a6fec2f492d76d7ff1b2cfcfbe2R31978 since we defined DUMP_BYTECODE 64 ourselves. Shall I rename our addition to 128 and keep the upstream one as 64?

**Review by bnoordhuis — APPROVED** [review]

**Comment by bnoordhuis** [comment]
> Does it hurt to have it?

It can. It inhibits some compiler optimizations around loops.

> Shall I rename our addition to 128 and keep the upstream one as 64?

Sure, seems fine to me.

**Comment by saghul** [comment]
> > Does it hurt to have it?
> 
> It can. It inhibits some compiler optimizations around loops.
> 
> > Shall I rename our addition to 128 and keep the upstream one as 64?
> 
> Sure, seems fine to me.

Ack, fixed both!

**Pull request merged**
