### PR TITLE
fix memory leaks in run-test262

### PR DESCRIPTION
**Pull request by chqrlie**

### CODE REVIEW

**Review by saghul — APPROVED** [review]

**Comment by chqrlie** [comment]
@saghul: The leaks are gone, but there is a persistent error with the Atomics:

test262/test/built-ins/Atomics/notify/notify-all-on-loc.js:13: strict mode: unexpected error: Test262Error:
   The value of `reports[NUMAGENT + 1]` is `"W timeout after Atomics.notify"`
   Expected `SameValue("W timeout before Atomics.notify", "W timeout after Atomics.notify")` to be `true`

**Comment by saghul** [comment]
Is that new? I didn't see it when I turned them on.

**Comment by chqrlie** [comment]
The valgrind test is only performed after the merge. You can see the failure(s) in the Actions tab.

**Comment by saghul** [comment]
Ah the valgring one! Sure thing, I'll take a look!

**Comment by saghul** [comment]
Looking at all recent runs (https://github.com/quickjs-ng/quickjs/actions/workflows/valgrind.yml) looks like it succeeded at least twice and failed also twice. My first suspicion here is timing, since valgrind is slooooow...

**Pull request merged**
