### PR TITLE
Fix declaring property named get/set/async

### PR DESCRIPTION
**Pull request by kvinwang**
```js    
    class P {
        get;
        get = () => "123";
    }
```
Got `SyntaxError: invalid property name`.
This PR fixes it.

### CODE REVIEW

**Comment by saghul** [comment]
Is this a port from bellard/quickjs ?

**Comment by kvinwang** [comment]
> Is this a port from bellard/quickjs ?

No, should I move this PR the the upstream? I submit it here because I use this fork in my project.
Looks like both repo are actively maintained. A bit confusing.

**Comment by saghul** [comment]
No need, I think this was fixed there too, that's why I asked.

**Comment by richarddd** [comment]
This fixes another pattern where we declare a property (without initalizing it) called `get`, and later initilizes is. My original QuickJS PR didn't consider this.  Should be added to upstream as well.

**Review by saghul — APPROVED** [review]

**Pull request merged**
