### PR TITLE
Fix strict name conformity cases

### PR DESCRIPTION
**Pull request by chqrlie**
- reject *future strict reserved words* in `js_parse_function_check_names()`.
- add tests for reserved names in tests/test_language.js
- update v8.txt

### CODE REVIEW

**Comment by bnoordhuis** [comment]
Shouldn't this be a bunch of separate commits? They're unrelated changes, right?

**Comment by chqrlie** [comment]
> Shouldn't this be a bunch of separate commits? They're unrelated changes, right?

Yes, I guess I should split this into multiple PRs

**Review by saghul — APPROVED** [review]

**Comment by chqrlie** [comment]
> Shouldn't this be a bunch of separate commits? They're unrelated changes, right?

Any further remarks?

**Review by bnoordhuis — APPROVED** [review]
:+1:

**Pull request merged**
