### PR TITLE
Add 'self' global

### PR DESCRIPTION
**Pull request by saghul**

### CODE REVIEW

**Comment by bnoordhuis** [comment]
Can you elaborate why that's necessary? `self` is a browser thing (as in `window.self`), not a JS thing.

**Comment by saghul** [comment]
No strong opinion. Other runtimes have it, and the wpt harness needed it so I thought why not? If we want to keep it simple we can drop it, I can't run the harness as-is anyway...

**Comment by bnoordhuis** [comment]
>  Other runtimes have it

You mean like V8? I'm reasonably sure it's inserted by Chromium, not V8. Node doesn't have it, for instance.

It'd be fine to have qjs add it to the JSContext but I'd rather not add non-standard things in the runtime itself.

**Comment by saghul** [comment]
I think Deno has it but you're right, let's drop it.

**Comment by bnoordhuis** [comment]
That makes sense because deno also has a window object, although that isn't [without its issues](https://github.com/denoland/deno/issues/13367).

**Pull request closed without merging**
