### PR TITLE
Exit on sanitizer trap, don't recover

### LINKED ISSUE #22: macOS ubsan errors, but test didn't fail
```
 ./qjs tests/test_closure.js
./qjs tests/test_language.js
quickjs.h:554:11: runtime error: 2.14748e+09 is outside the range of representable values of type 'int'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior quickjs.h:554:11 in 
./qjs tests/test_builtin.js
quickjs.h:554:11: runtime error: 1.5061e+12 is outside the range of representable values of type 'int'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior quickjs.h:554:11 in 
./qjs tests/test_loop.js
./qjs tests/test_std.js
./qjs tests/test_worker.js
./qjs --bignum tests/test_op_overloading.js
./qjs --bignum tests/test_bignum.js
```

### PR DESCRIPTION
**Pull request by bnoordhuis**
Fixes: https://github.com/quickjs-ng/quickjs/issues/22

### CODE REVIEW

**Comment by bnoordhuis** [comment]
Does what it's supposed to do. The trap is the `val = (int32_t)d;` cast in JS_NewFloat64(). I'll see if I can fix that.

**Review by saghul — APPROVED** [review]

**Comment by bnoordhuis** [comment]
Oh brother.... one source of UB down, at least one more to go.

**Comment by bnoordhuis** [comment]
@saghul okay, should be good to go now. PTAL.

**Review by saghul — APPROVED** [review]
LGTM!

**Comment by saghul** [comment]
Awesome!

**Pull request merged**
