### PR TITLE
Add LTO support to CMake build

### PR DESCRIPTION
**Pull request by saghul**

### CODE REVIEW

**Comment by bnoordhuis** [comment]
I'm curious, does LTO make a difference in the quality of the generated code? It's effectively a single code unit already.

Or is this for downstream consumers? Wouldn't they normally enforce that through CMAKE_C_FLAGS?

**Comment by saghul** [comment]
TBH I haven't checked. Went for compatibility with the existing makefile.

We could table this for if / when there are more units ;-)

**Comment by bnoordhuis** [comment]
I strongly lean towards "do nothing until someone complains" :-)

**Comment by bnoordhuis** [comment]
Oh, now that I think about it: LTO produced (and still produces) no end of build and runtime issues with node due to bugs in compilers and linkers, so... yeah.

**Pull request closed without merging**
