### PR TITLE
Remove unnecessary parameters

### PR DESCRIPTION
**Pull request by hxcliff**
Enhanced msvc cross-compile compatibility

### CODE REVIEW

**Comment by saghul** [comment]
Can you clarify how this helps?

**Comment by hxcliff** [comment]
> Can you clarify how this helps?

This msvc version of the function does not depend on tz, tz was introduced (and not used) in the linux version of the function, where if it was for binary compatibility I think it could be retained but the function name has changed and there is no binary compatibility issue. Then in a cross-compiled environment it even brings some compiler alerts

**Comment by hxcliff** [comment]
And in linux the tz parameter is only used in the kernel, so I think it's possible to remove the unnecessary parameter

**Review by bnoordhuis — APPROVED** [review]
Seems fine to me.

**Pull request merged**
