### PR TITLE
Add valgrind to CI

### LINKED ISSUE #71: Run test suite under valgrind
Valgrind catches bugs that {A,M,UB}San won't catch. The downside is it's sloooow and maybe not something we want to run for every commit.

Test how long it takes on GHA. If it's beyond reasonable, then run it daily as a [GHA cron job](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule)?

### PR DESCRIPTION
**Pull request by saghul**
Fixes: https://github.com/quickjs-ng/quickjs/issues/71

### CODE REVIEW

**Comment by saghul** [comment]
1h 32m 😅 

Do we think that is acceptable? @bnoordhuis @chqrlie

**Comment by chqrlie** [comment]
> 1h 32m 😅
> 
> Do we think that is acceptable? @bnoordhuis @chqrlie

I would say no, this makes the CI too long for every patch request.  Can we make this test optional and trigger it manually?

**Comment by saghul** [comment]
> Can we make this test optional and trigger it manually?

Yes, it's possible to make a dedicated workflow that requires manual dispatch.

**Comment by bnoordhuis** [comment]
Or, alternatively, run it post-merge when things get committed to the master branch. That way it doesn't hold up development.

There are ways to speed up valgrind a little, like e.g. setting `--num-callers=5`, but it probably won't make a huge difference.

And, on the flip side, `--track-origins=yes` would definitely be useful (tells you not just that you have an uninitialized value but also where it comes from) but makes valgrind at least twice as slow.

**Comment by saghul** [comment]
> Or, alternatively, run it post-merge when things get committed to the master branch. That way it doesn't hold up development.

I like that. I'll make the change.



> And, on the flip side, `--track-origins=yes` would definitely be useful (tells you not just that you have an uninitialized value but also where it comes from) but makes valgrind at least twice as slow.

Let's have it!

**Comment by saghul** [comment]
Updated as per @bnoordhuis 's suggestions. I also enabled manual dispatch of the workflow, in case we want to run it without pushing to master, for whatever reason.

**Review by chqrlie — APPROVED** [review]

**Pull request merged**
