### PR TITLE
Implement Iterator.prototype.flatMap

### PR DESCRIPTION
**Pull request by saghul**

### CODE REVIEW

**Comment by saghul** [comment]
Phew, this was the hardest of them all...

@bnoordhuis Proposal: aftewr this lands, I'll update some docs and cut a release. 

Then do a bit of cleanup, I see some opportunities to DRY some code. WDYT? Anything else you'd like to do before releasing?

**Comment by saghul** [comment]
Valgrind run, just in case: https://github.com/quickjs-ng/quickjs/actions/runs/11826283390

**Review by bnoordhuis — APPROVED** [review]
:+1:

**Comment by bnoordhuis** [comment]
> Anything else you'd like to do before releasing?

I'd like to fix #683 (should be trivial) and I've been thinking about releasing amalgamated builds but that doesn't have to hold up _this_ release. I'll open an issue to discuss.

**Comment by bnoordhuis** [comment]
Oh, I guess we still have a few Iterator failures in test262_errors.txt, with a few more after updating test262. Maybe they're harmless but it'd be good to look into them before cutting a release.

**Comment by saghul** [comment]
> Oh, I guess we still have a few Iterator failures in test262_errors.txt, with a few more after updating test262. Maybe they're harmless but it'd be good to look into them before cutting a release.

I'll take a look. Some of them were there before and some were fringe cases but I'll double check!

**Pull request merged**
